---
- name: Install Docker machine driver 
  include_tasks: "{{ ansible_os_family }}_driver.yml"

- name: Check if minishift binary exists
  stat:
    path: "{{ minishift_dest }}/minishift"
  register: minishift_client

- name: Get minishift assets
  include_tasks: get_ms_assets.yml

- name: Install minishift 
  include_tasks: install_minishift.yml
  when: not minishift_client.stat.exists or minishift_force_install 

- name: Remove existing minishift instance 
  include_tasks: isrunning.yml 

- name: Run minishift
  command: "minishift start --{{ minishift_start_options | join(' --') }}"
  environment:
    # Enable mounting /Users to the VM on OSX
    XHYVE_VIRTIO_9P: true
  register: minishift_out

- name: Give cluster-admin to developer
  include_tasks: grant_admin.yml 

- name: Check if oc binary exists
  stat:
    path: "{{ openshift_client_dest }}/oc" 
  register: oc_client

- name: Copy latest oc client from ~/.minishift
  include_tasks: copy_oc_client.yml 
  when: not oc_client.stat.exists or openshift_force_client_copy

- name: Create objects
  include_tasks: create_objects.yml

- name: Add entry to /etc/hosts
  include_tasks: add_hostname.yml  

- name: Filter start output
  include_tasks: filter_output.yml

- name: Show output
  debug:
    var: filtered_output.stdout_lines 

